### ISSUE TITLE
MPI source error running make

### ISSUE THREAD

**Issue by Joseph459459** [UKFELs/Puffin#85] opened 2022-05-20 00:24 UTC
When I try to run make && make install I run into the following type of error in DParallelSetUp.f90

  501 |     CALL MPI_ALLGATHER(in1,1,MPI_INT_HIGH, &
      |                       1
......
  523 |     CALL MPI_ALLGATHER(in1,1,MPI_DOUBLE_PRECISION, &
      |                       2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).

I am new to fortran - is there no implicit type-casting?

Attempt at solution:
I am on a HPC cluster so I tried to make sure that different MPI versions weren't conflicting. The build itself completed without error. There is only a deprecation warning for CMake, and it also tells me it doesn't use my manually specified fortran compiler.
The openmpi version is 4.1.2, gcc is 10.
fftw3 is version 3.3.9 and uses openmpi 4.0.5, gcc 10.2.

**Comment by mightylorenzo** [comment] 2022-05-21 00:46
Hi! In Fortran there's no implicit type casting in method signatures. 

Can you attach the command history and output? I suspect it's the fortran compiler that you're being told is different from the version you're trying to manually specify.

(Another issue here is that we are doing 'include mpif.h' (to support some legacy libs/compilers) to import the MPI lib routines, rather than the more modern 'use MPI' which does proper compile-time checking, so it's probably only caught at the link stage? Changing this won't fix the issue you're having though, I don't think...)

**Comment by Joe459** [comment] 2022-05-23 15:51
Hi mightylorenzo,

I have successfully compiled Puffin using gcc version 8.2, openmpi version 2.1, and HDF5 1.8.

However, now I'm encountering the following kind of linking errors caused by HDF5:

`[  1%] Linking Fortran executable puffin
CMakeFiles/puffin.dir/H5in.f90.o: In function `__h5in_MOD_readh5fieldfilesingledump':
H5in.f90:(.text+0x1be): undefined reference to `h5pset_fapl_mpio_f_'
H5in.f90:(.text+0xc27): undefined reference to `h5pset_dxpl_mpio_f_'
H5in.f90:(.text+0x1115): undefined reference to ``h5pset_dxpl_mpio_f_``

Here is the corresponding cmake output log for the successful compile / unsuccessful linking:
[cmake-puffin.txt](https://github.com/UKFELs/Puffin/files/8756074/cmake-puffin.txt)

It would seem that all the correct libraries are recognized by scimake. Is this perhaps an HDF5 version compatibility issue?

**Comment by mightylorenzo** [comment] 2022-05-26 19:14
It could be, although those constants are supplied by the MPI lib itself. Usually is see those types of errors are when scimake/cmake gets confused about which versions of each lib to point to. If possible, can you post the whole compile/link command history and output (including output of running make etc)

**Closed** 2024-09-24 23:24 UTC
